# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.12

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  publish:
    docker:
      - image: circleci/node:11.13

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/repo/.npmrc
      - run: npm publish;

workflows:
  version: 2
  build_publish:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - master
